spin_manifest_version = 2

[application]
name = "foo"
version = "0.1.0"
authors = ["Matthew Fisher <matt.fisher@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "foo"

[component.foo]
source = "target/wasm32-wasip1/release/foo.wasm"
allowed_outbound_hosts = []
[component.foo.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
